'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {QRCodeSVG} from 'qrcode.react'
import {api,getMe,getWhatsappStatus,connectWhatsapp,getToken} from '@/lib/api'
export default function ConnectWeb(){
 const [user,setUser]=useState<any>(null),[session,setSession]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[logs,setLogs]=useState<any[]>([])
 async function refresh(){const s=await getWhatsappStatus();setSession(s);return s}
 useEffect(()=>{if(!getToken()){window.location.replace('/auth/login?next=%2Fconnect');return}let alive=true,inflight=false;getMe().then(u=>{if(alive)setUser(u)}).catch(e=>setError(e.message));const poll=async()=>{if(inflight)return;inflight=true;try{const s=await getWhatsappStatus();if(alive)setSession(s)}catch(e:any){if(alive)setError(e.message)}finally{inflight=false}};poll();const timer=setInterval(poll,2000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{alive=false;clearInterval(timer);clearInterval(clock)}},[])
 async function generate(){if(busy)return;setBusy(true);setError('');try{await connectWhatsapp();await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const seconds=Math.max(0,Math.ceil((Date.parse(session?.qr_expires_at||'')-now)/1000))
 return <main className="connection-web"><section><Link href="/messages" className="connection-back">← Abrir o app</Link><h1>Conectar WhatsApp</h1><p>Abra esta página no computador e escaneie com o WhatsApp do celular.</p>{user&&<div className="connection-account">Conta: <strong>{user.email}</strong><small>Use esta mesma conta no PWA.</small></div>}{error&&<p role="alert" className="connection-error">{error}</p>}{session?.error_message&&<p role="alert" className="connection-error">{session.error_message}</p>}
 {session?.status==='connected'?<div className="connection-success"><h2>WhatsApp conectado</h2><p>O PWA desta conta acompanha a conexão automaticamente.</p><p>{session.history_received_at?'Histórico recebido do WhatsApp.':session.history_error||'Aguardando o WhatsApp enviar o histórico. Mantenha o celular online.'}</p><Link href="/messages">Abrir conversas →</Link><button className="block mt-5 text-sm underline" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/whatsapp/disconnect',{method:'DELETE'});await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Desconectar WhatsApp</button></div>:<><div className="connection-qr">{session?.qr_code&&seconds>0?<><QRCodeSVG value={session.qr_code} size={244}/><span>Escaneie agora · {seconds}s</span></>:<p>{session?.status==='connecting'?'Preparando QR Code…':'Gere o código para conectar.'}</p>}</div><button className="connection-button" onClick={generate} disabled={busy}>{busy?'Gerando…':session?.qr_code?'Atualizar QR Code':'Gerar QR Code'}</button></>}
 <ol><li>No WhatsApp, abra <strong>Configurações → Dispositivos conectados</strong>.</li><li>Toque em <strong>Conectar dispositivo</strong> e escaneie o código.</li><li>Abra o PWA com a mesma conta mostrada acima.</li></ol><details onToggle={e=>{if(e.currentTarget.open)api('/api/assistant/diagnostics').then(setLogs).catch(()=>{})}}><summary>Diagnóstico de conexão e voz</summary><button onClick={()=>api('/api/assistant/diagnostics').then(setLogs).catch(e=>setError(e.message))}>Atualizar diagnóstico</button><p>Somente eventos técnicos; sem conversas, senhas ou chaves.</p>{logs.length?logs.map((l,i)=><div className="diagnostic-line" key={i}>{new Date(l.created_at).toLocaleTimeString('pt-BR')} · {l.event}{l.code?` · ${l.code}`:''}</div>):<p>Nenhum evento registrado.</p>}</details></section></main>
}
