'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { api } from '@/lib/api'
import { icons } from '@/components/nexo-ui'
const { Sparkles, ArrowLeft } = icons
export default function Reports() {
  const [reports, setReports] = useState<any[]>([]), [current, setCurrent] = useState<any>(null), [date, setDate] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  useEffect(() => { const today = new Date(); setDate(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`); api('/api/assistant/reports').then(rows => { setReports(rows); setCurrent(rows[0] || null) }).catch(e => setError(e.message)) }, [])
  async function generate() { setBusy(true); setError(''); try { const report = await api('/api/assistant/reports', { method: 'POST', body: JSON.stringify({ date }) }); setCurrent(report); setReports(await api('/api/assistant/reports')) } catch (e: any) { setError(e.message) } finally { setBusy(false) } }
  return <main className="nexo-page reports-page"><Link href="/messages" className="suggest-link"><ArrowLeft size={17} />Conversas</Link><div className="page-heading"><div><p className="eyebrow">O SEU DIA, COM CLAREZA</p><h1>Resumo do dia<span>.</span></h1></div></div><p className="muted">Pedidos, assuntos importantes e próximos passos das mensagens recebidas.</p><section className="nexo-card mt-6"><div className="report-controls"><label>Dia do relatório<input aria-label="Dia do relatório" className="nexo-input" type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button className="nexo-primary" disabled={busy || !date} onClick={generate}><Sparkles size={18} />{busy ? 'Organizando seu dia…' : 'Gerar relatório'}</button></div><p className="helper">Usa a opção de IA escolhida em Perfil. Um relatório por dia, salvo para consultar novamente sem gerar outra resposta. Até 300 mensagens disponíveis, no fuso da sua conta. Geração manual nesta versão.</p></section>{error && <p role="alert" className="nexo-error">{error}</p>}<div className="report-layout"><aside>{reports.map(r => <button key={r.id} onClick={() => setCurrent(r)} className={current?.id === r.id ? 'selected' : ''}><strong>{String(r.report_date).slice(0,10).split('-').reverse().join('/')}</strong><small>{r.message_count} mensagens</small></button>)}</aside><article className="nexo-card">{current ? <><span className="small-badge">RELATÓRIO SALVO</span><h2 className="mt-5">{String(current.report_date).slice(0,10).split('-').reverse().join('/')}</h2><p className="report-content">{current.content}</p><p className="helper">Gerado em {new Date(current.created_at).toLocaleString('pt-BR')}. Novas mensagens posteriores não são incluídas neste relatório.</p></> : <div className="nexo-empty"><Sparkles size={32} /><h2>Um dia inteiro. Só o essencial.</h2><p>Escolha uma data e peça à Luna para organizar o que aconteceu.</p></div>}</article></div></main>
}
